export const GET_WORKERS_REQUEST = "GET_WORKERS_REQUEST";
export const GET_WORKERS_SUCCESS = "GET_WORKERS_SUCCESS";
export const GET_WORKERS_FAILURE = "GET_WORKERS_FAILURE";

export const PUT_WORKER_INFO_REQUEST = "PUT_WORKER_INFO_REQUEST";
export const PUT_WORKER_INFO_SUCCESS = "PUT_WORKER_INFO_SUCCESS";
export const PUT_WORKER_INFO_FAILURE = "PUT_WORKER_INFO_FAILURE";
